### ISSUE TITLE
Option source add CSS folder to my path

### ISSUE THREAD

**Issue by DCKT** [sass/node-sass-middleware#57]
Hi,

I used the module with express 4 and when I put the path to the source folder it suffix him with the css folder : 

Here is the code :
````javascript
  app.use(sassMiddleware({
    src: path.join(__dirname,  '../assets/sass'),
    dest: path.join(__dirname,  '../assets'),
    debug: true,
    outputStyle: 'expanded',
    prefix: '/assets',
  }));
```
![image](https://cloud.githubusercontent.com/assets/1548421/9882731/7bf84578-5bd6-11e5-9a43-8acca216ff6a.png)

Is it a normal feature ? Or maybe i'm doing something wrong ?
Thanks

**Comment by am11** [comment]
Hi, I think there is nothing wrong with your configuration. However, it seems like your web request is `/assets/css/main.css` instead of `/assets/main.css`. 
If you intend to consume from `/assets/css/main.css` on client-side, then either create a URL rewrite rule (or control it with MVC route) to map `/assets/css` to `/assets` before the preprocessing, or set `dest` to `path.join(__dirname, '../assets')` (or IMO even better use `path.resolve` like: `path.resolve(__dirname, '../assets')`).

**Comment by DCKT** [comment]
Hello,

You were right, I changed the prefix parameter to **/assets/css** and it works well !

Thanks

**Comment by am11** [comment]
No problem. Glad to hear that it resolved your issue. :)
FYI: [v0.9.5 <kbd>tag</kdb>](https://github.com/sass/node-sass-middleware/releases/tag/v0.9.5) is just released with more options and improvements. Please try it out let us know if you encounter any issue.
