### ISSUE TITLE
Cannot pass `includePaths` to node-sass

### ISSUE THREAD

**Issue by piglovesyou** [sass/node-sass-middleware#60]
It would be nice when we are able to pass `includePaths` for our `@import`.

**Comment by am11** [comment]
Although the project's README does not spell this option out explicitly, but it does note:

> For full list of options from original node-sass project go [here](https://github.com/sass/node-sass)

Which means we can potentially pass-through any option from middleware over to node-sass:

```javascript
require('node-sass-middleware')({
    src: __dirname,
    includePaths: ['some/disjoint/rel/or/abs/path/to/dir/1', 'another/path', 'and/so/on']
})
```

I am going to close this issue, since there is nothing further to improve in middleware's option handling. If you feel differently about the state of documentation, please send  a PR with usage notes for this particular option, test and example usage etc.

**Comment by piglovesyou** [comment]
Oh I didn't notice the link. That is enough for me, thanks.
