### ISSUE TITLE
Timeouts upon multiple requests

### ISSUE THREAD

**Issue by marclipovsky** [sass/node-sass-middleware#64]
I'm on node-sass-middleware@0.9.7 and when more than three simultaneous requests are made a timeout occurs on all css files and every request after that until I start the server over. Right now I'm using connect package to use the middleware with. I've been able to reproduce the issue by refreshing a single css file multiple times quickly. When I run it with debug the source, dest and read outputs show up but no response.

I was going to try out the middleware with express but the connect and express examples are not up to date with the current version of connect and express.

**Comment by am11** [comment]
Thanks for the report @marclipovsky.

It seems to be something related to the part of functionality, where we are relying on the last modified time of input file and skip the compilation step if the file hasn't changed.

If you have spotted the issue and have a fix handy, would you please send a pull-request? :)
Otherwise, can you please make self contained steps to repro ([SSCCE](http://sscce.org/)) for this issue?

Regarding the repo examples, @Xiphe has recently added a new one: https://github.com/sass/node-sass-middleware/pull/66. Please try it out. I agree that the example usage should keep in sync with the latest versions of connect and express APIs. Currently it is a mixture of old, very old and slightly old versions etc.
