### ISSUE TITLE
Destination CSS file doesn't exist

### ISSUE THREAD

**Issue by NetOperatorWibby** [sass/node-sass-middleware#70]
Hey everyone,

I would like my Sass files to be compiled to a different folder, not the same folder as my Sass files, but `dest` isn't respected for some reason. Neither is `outFile`. Has anyone else gotten this to work?

**Comment by am11** [comment]
Hi, can you share an example which is failing?

I have just tested https://github.com/andrew/node-sass-example with latest stable `node-sass-middleware` and `connect` (-> `npm i node-sass-middleware connect`):

Changed:

```js
var destPath = __dirname + '/public/styles/';
```

to:

```js
var destPath = __dirname + '/public/new-styles/';
```

in [`server.js - line 5`](https://github.com/andrew/node-sass-example/blob/acc03ae/server.js#L5) and same line number in [index.html](https://github.com/andrew/node-sass-example/blob/master/public/index.html#L5) as `"new-styles/main.css"` creates a new directory `{cwd}/public/new-style` with `main.css` on subsequent request.

**Comment by NetOperatorWibby** [comment]
I was doing the exact same thing as the example you've tested with, but I'm not using Connect, I'm using FeathersJS.

**Comment by bnolan** [comment]
I'm having this on ocassional reloads using the example express code. Is this middleware kind of broken?

**Comment by BodySplash** [comment]
I had the same issue, but then I realised it was just a matter of setting correctry the "prefix" options. 
My pages look for css files with a path like "/styles/<file>.css"

here is my working conf : 

`{
    src: path.join(__dirname, 'scss'),
    dest: path.join(__dirname, 'public', 'styles'),
    prefix: '/styles'

  }`

Hope that helps

**Comment by theshadow124** [comment]
I'm having the same issue, here is my middleware code:

```
  // adding the sass middleware
  app.use(sassMiddleware({
  	/* Options */
  	src: path.join(__dirname, "public/sass"),
  	dest: path.join(__dirname, "public/css"),
  	debug: true,
  	outputStyle: 'compressed',
    prefix:  '/static/css'  // Where prefix is at <link rel="stylesheets" href="prefix/style.css"/>
}));

  app.use('/static', express.static('public'))
```

I've tried changing the prefix around with no luck, but I get this in the debug window:

```
  source: ~\public\sass\style.scss
  dest: ~\public\css\style.css
  read: ~\public\css\style.css
```
But the css file is never created and the website doesnt recive the code.

**Comment by am11** [comment]
@theshadow124, here is how I managed to make your example work:

File - `c:\temp\projectx\my-server.js`:

```javascript
var sassMiddleware = require('../../middleware');
var app = require('express')();
var serveStatic = require('serve-static');
var join = require('path').join;
var http = require('http');
var port = process.env.PORT || 8000;

var myPrefix = '/static/css';

// Sass middleware
app.use(sassMiddleware({
  /* Options */
  src: join(__dirname, 'public/sass'),
  dest: join(__dirname, 'public/css'),
  debug: true,
  outputStyle: 'compressed',
  prefix: myPrefix 
}));

// static middleware
app.use(myPrefix, serveStatic(__dirname));

// start server
http.createServer(app).listen(port);
```

Assuming you have `c:\temp\projectx\public\sass\test.scss`  source file; in a web browser, navigate to `http://localhost:8000/static/css/public/css/test.css` (notice the format: `{protocol}://{host}:{port}/{prefix}/{destinationSlug}/{cssFilename}.css`).

**Comment by am11** [comment]
Another thing to note is if we navigate to `http://localhost:8000/static/css/test.css` (without the destination-slug; the relative path of destination with respect to `__dirname`), we still get the response from server for the first time only. If we refresh the page, it will return 404.

This is because the when Sass middleware compiles the file, it writes the output to disk as well as return the in-memory buffer to the caller. But on the subsequent refresh, Sass middleware skips the compilation (because the source hasn't changed), it calls the `next()` middleware (the static middleware), which relies on the pure destination path.

Therefore, it is imperative to include that `destinationSlug` in the calling URL to get the response reliably.

**Comment by theshadow124** [comment]
I never get the file no matter what, from my above post, it never saves the file even once.

**Comment by am11** [comment]
Ok, disregard my comment about destination slug (removed). Here is the example project: [smw-test.zip](https://github.com/sass/node-sass-middleware/files/602666/smw-test.zip)

* Extract zip to `smw-test.zip` to `smw-test`.
* Then execute `npm i && node my-server`.
* Browse to `http://localhost:8000/static/css/test.css`.

I was mistaken, we don't need to specify destination slug and static middleware should be configured as `app.use(myPrefix, serveStatic(destination));` (fixed in above comment as well). Also the source and destination follow the same sub-directory structure, so if you call something like `http://localhost:8000/static/css/some/sub/directory/test.css`, then it looks the source file at the same structure under source directory like `public/sass/some/sub/directory/test.scss`.

**Comment by theshadow124** [comment]
Great, I'm convinced it is some sort of permission issue at this point, even though I'm on windows. I ran your script, it ran fine, copied and pasted the content of your server file into mine and then it does the same thing. I've checked, the files are NOT read only.

I'll keep screwing with it.

**Comment by theshadow124** [comment]
update to my issue, my filename was .sass, I thought this was valid, renaming to .scss fixed the issue

**Comment by am11** [comment]
@NetOperatorWibby, I have tested the current behavior with connect and express multiple times: https://github.com/sass/node-sass-middleware/issues/70#issuecomment-261822665. Please try reconfiguring feather.js with node-sass-middleware v0.10.x. I am closing this for now.

Feel free to reopen or create a new issue (with steps to repro), if you are still getting problems.

**Comment by NetOperatorWibby** [comment]
@am11 I'm not using this anymore but I'm glad it works well now!
