### ISSUE TITLE
Warn users that serve static must be after sass middleware

### ISSUE THREAD

**Issue by danawoodman** [sass/node-sass-middleware#71]
If you load the `express.static` middleware before `node-sass-middleware`, the middleware doesn't work. It must be loaded *before* serving static files.

In other words, this fails:

```js
app.use(express.static(config.PUBLIC_PATH, { index: false }))
app.use(sassMiddleware({
  src: path.join(__dirname, 'styles'),
  dest: config.PUBLIC_PATH,
}))
```

But this works:

```js
app.use(sassMiddleware({
  src: path.join(__dirname, 'styles'),
  dest: config.PUBLIC_PATH,
}))
app.use(express.static(config.PUBLIC_PATH, { index: false }))
```

**Comment by am11** [comment]
Briefly, this is not possible for node-sass middleware to warn the user.

```javascript
app.use(express.static(config.PUBLIC_PATH, { index: false }))
// if previous middleware handled the request successfully,
// the request will never reach the next SassMiddleware
//
app.use(sassMiddleware({
  src: path.join(__dirname, 'styles'),
  dest: config.PUBLIC_PATH,
}))
```

This is the default middleware pattern, where precedence works like:

* if n<sup>th</sup> middleware handles the request successfully, n+1<sup>th</sup> middleware shall not be executed.
* if n<sup>th</sup> middleware does not want to handle the request, it should bail out and call `next()` to reach n+1<sup>th</sup> middleware and since so forth.

Thus, essentially consumers are in control of the application flow and the middleware should be arranged as they see fit.

**Comment by danawoodman** [comment]
Sorry, more clearly I meant it should be mentioned in the README that this is required so new users know that they need to double check the order

**Comment by danawoodman** [comment]
Just created a PR to add the note

**Comment by am11** [comment]
Thanks @danawoodman! :tada:

**Comment by danawoodman** [comment]
👍 😸
